# Configuration for weekly-digest - https://github.com/apps/weekly-digest
publishDay: mon
canPublishIssues: true
canPublishPullRequests: true
canPublishContributors: false
canPublishStargazers: false
canPublishCommits: true
canPublishReleases: false
